//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the raven_2 package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __raven_2__MYSTUFFCONFIG_H__
#define __raven_2__MYSTUFFCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace raven_2
{
  class MyStuffConfigStatics;
  
  class MyStuffConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(MyStuffConfig &config, const MyStuffConfig &max, const MyStuffConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const MyStuffConfig &config1, const MyStuffConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, MyStuffConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const MyStuffConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MyStuffConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const MyStuffConfig &config) const = 0;
      virtual void getValue(const MyStuffConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T MyStuffConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (MyStuffConfig::* field);

      virtual void clamp(MyStuffConfig &config, const MyStuffConfig &max, const MyStuffConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const MyStuffConfig &config1, const MyStuffConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, MyStuffConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const MyStuffConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MyStuffConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const MyStuffConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const MyStuffConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, MyStuffConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, MyStuffConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<MyStuffConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(MyStuffConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("shoulder_l"==(*_i)->name){shoulder_l = boost::any_cast<double>(val);}
        if("elbow_l"==(*_i)->name){elbow_l = boost::any_cast<double>(val);}
        if("insertion_l"==(*_i)->name){insertion_l = boost::any_cast<double>(val);}
        if("roll_l"==(*_i)->name){roll_l = boost::any_cast<double>(val);}
        if("wrist_l"==(*_i)->name){wrist_l = boost::any_cast<double>(val);}
        if("grasp1_l"==(*_i)->name){grasp1_l = boost::any_cast<double>(val);}
        if("grasp2_l"==(*_i)->name){grasp2_l = boost::any_cast<double>(val);}
        if("shoulder_r"==(*_i)->name){shoulder_r = boost::any_cast<double>(val);}
        if("elbow_r"==(*_i)->name){elbow_r = boost::any_cast<double>(val);}
        if("insertion_r"==(*_i)->name){insertion_r = boost::any_cast<double>(val);}
        if("roll_r"==(*_i)->name){roll_r = boost::any_cast<double>(val);}
        if("wrist_r"==(*_i)->name){wrist_r = boost::any_cast<double>(val);}
        if("grasp1_r"==(*_i)->name){grasp1_r = boost::any_cast<double>(val);}
        if("grasp2_r"==(*_i)->name){grasp2_r = boost::any_cast<double>(val);}
      }
    }

    double shoulder_l;
double elbow_l;
double insertion_l;
double roll_l;
double wrist_l;
double grasp1_l;
double grasp2_l;
double shoulder_r;
double elbow_r;
double insertion_r;
double roll_r;
double wrist_r;
double grasp1_r;
double grasp2_r;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double shoulder_l;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double elbow_l;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double insertion_l;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double roll_l;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double wrist_l;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double grasp1_l;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double grasp2_l;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double shoulder_r;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double elbow_r;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double insertion_r;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double roll_r;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double wrist_r;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double grasp1_r;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double grasp2_r;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("MyStuffConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const MyStuffConfig &__max__ = __getMax__();
      const MyStuffConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const MyStuffConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const MyStuffConfig &__getDefault__();
    static const MyStuffConfig &__getMax__();
    static const MyStuffConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const MyStuffConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void MyStuffConfig::ParamDescription<std::string>::clamp(MyStuffConfig &config, const MyStuffConfig &max, const MyStuffConfig &min) const
  {
    return;
  }

  class MyStuffConfigStatics
  {
    friend class MyStuffConfig;
    
    MyStuffConfigStatics()
    {
MyStuffConfig::GroupDescription<MyStuffConfig::DEFAULT, MyStuffConfig> Default("Default", "", 0, 0, true, &MyStuffConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.shoulder_l = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.shoulder_l = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.shoulder_l = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("shoulder_l", "double", 0, "An offet to add to the shoulder_l", "", &MyStuffConfig::shoulder_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("shoulder_l", "double", 0, "An offet to add to the shoulder_l", "", &MyStuffConfig::shoulder_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.elbow_l = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.elbow_l = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.elbow_l = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("elbow_l", "double", 0, "An offet to add to the elbow_l", "", &MyStuffConfig::elbow_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("elbow_l", "double", 0, "An offet to add to the elbow_l", "", &MyStuffConfig::elbow_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.insertion_l = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.insertion_l = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.insertion_l = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("insertion_l", "double", 0, "An offet to add to the insertion_l", "", &MyStuffConfig::insertion_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("insertion_l", "double", 0, "An offet to add to the insertion_l", "", &MyStuffConfig::insertion_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.roll_l = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.roll_l = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.roll_l = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("roll_l", "double", 0, "An offet to add to the roll_l", "", &MyStuffConfig::roll_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("roll_l", "double", 0, "An offet to add to the roll_l", "", &MyStuffConfig::roll_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.wrist_l = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.wrist_l = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.wrist_l = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("wrist_l", "double", 0, "An offet to add to the wrist_l", "", &MyStuffConfig::wrist_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("wrist_l", "double", 0, "An offet to add to the wrist_l", "", &MyStuffConfig::wrist_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.grasp1_l = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.grasp1_l = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.grasp1_l = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp1_l", "double", 0, "An offet to add to the grasp1_l", "", &MyStuffConfig::grasp1_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp1_l", "double", 0, "An offet to add to the grasp1_l", "", &MyStuffConfig::grasp1_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.grasp2_l = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.grasp2_l = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.grasp2_l = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp2_l", "double", 0, "An offet to add to the grasp2_l", "", &MyStuffConfig::grasp2_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp2_l", "double", 0, "An offet to add to the grasp2_l", "", &MyStuffConfig::grasp2_l)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.shoulder_r = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.shoulder_r = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.shoulder_r = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("shoulder_r", "double", 0, "An offet to add to the shoulder_r", "", &MyStuffConfig::shoulder_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("shoulder_r", "double", 0, "An offet to add to the shoulder_r", "", &MyStuffConfig::shoulder_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.elbow_r = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.elbow_r = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.elbow_r = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("elbow_r", "double", 0, "An offet to add to the elbow_r", "", &MyStuffConfig::elbow_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("elbow_r", "double", 0, "An offet to add to the elbow_r", "", &MyStuffConfig::elbow_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.insertion_r = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.insertion_r = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.insertion_r = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("insertion_r", "double", 0, "An offet to add to the shoulder_r", "", &MyStuffConfig::insertion_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("insertion_r", "double", 0, "An offet to add to the shoulder_r", "", &MyStuffConfig::insertion_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.roll_r = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.roll_r = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.roll_r = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("roll_r", "double", 0, "An offet to add to the roll_r", "", &MyStuffConfig::roll_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("roll_r", "double", 0, "An offet to add to the roll_r", "", &MyStuffConfig::roll_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.wrist_r = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.wrist_r = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.wrist_r = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("wrist_r", "double", 0, "An offet to add to the wrist_r", "", &MyStuffConfig::wrist_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("wrist_r", "double", 0, "An offet to add to the wrist_r", "", &MyStuffConfig::wrist_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.grasp1_r = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.grasp1_r = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.grasp1_r = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp1_r", "double", 0, "An offet to add to the grasp1_r", "", &MyStuffConfig::grasp1_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp1_r", "double", 0, "An offet to add to the grasp1_r", "", &MyStuffConfig::grasp1_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.grasp2_r = -50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.grasp2_r = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.grasp2_r = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp2_r", "double", 0, "An offet to add to the grasp2_r", "", &MyStuffConfig::grasp2_r)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp2_r", "double", 0, "An offet to add to the grasp2_r", "", &MyStuffConfig::grasp2_r)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(MyStuffConfig::AbstractGroupDescriptionConstPtr(new MyStuffConfig::GroupDescription<MyStuffConfig::DEFAULT, MyStuffConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<MyStuffConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<MyStuffConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<MyStuffConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    MyStuffConfig __max__;
    MyStuffConfig __min__;
    MyStuffConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const MyStuffConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static MyStuffConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &MyStuffConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const MyStuffConfig &MyStuffConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const MyStuffConfig &MyStuffConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const MyStuffConfig &MyStuffConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<MyStuffConfig::AbstractParamDescriptionConstPtr> &MyStuffConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<MyStuffConfig::AbstractGroupDescriptionConstPtr> &MyStuffConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const MyStuffConfigStatics *MyStuffConfig::__get_statics__()
  {
    const static MyStuffConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = MyStuffConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __MYSTUFFRECONFIGURATOR_H__
