//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the raven_2 package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __raven_2__MYSTUFFCONFIG_H__
#define __raven_2__MYSTUFFCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace raven_2
{
  class MyStuffConfigStatics;
  
  class MyStuffConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(MyStuffConfig &config, const MyStuffConfig &max, const MyStuffConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const MyStuffConfig &config1, const MyStuffConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, MyStuffConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const MyStuffConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MyStuffConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const MyStuffConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T MyStuffConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (MyStuffConfig::* field);

      virtual void clamp(MyStuffConfig &config, const MyStuffConfig &max, const MyStuffConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const MyStuffConfig &config1, const MyStuffConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, MyStuffConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const MyStuffConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, MyStuffConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const MyStuffConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 13 "../cfg/MyStuff.cfg"
      double shoulder_l;
//#line 14 "../cfg/MyStuff.cfg"
      double elbow_l;
//#line 15 "../cfg/MyStuff.cfg"
      double insertion_l;
//#line 16 "../cfg/MyStuff.cfg"
      double roll_l;
//#line 17 "../cfg/MyStuff.cfg"
      double wrist_l;
//#line 18 "../cfg/MyStuff.cfg"
      double grasp1_l;
//#line 19 "../cfg/MyStuff.cfg"
      double grasp2_l;
//#line 21 "../cfg/MyStuff.cfg"
      double shoulder_r;
//#line 22 "../cfg/MyStuff.cfg"
      double elbow_r;
//#line 23 "../cfg/MyStuff.cfg"
      double insertion_r;
//#line 24 "../cfg/MyStuff.cfg"
      double roll_r;
//#line 25 "../cfg/MyStuff.cfg"
      double wrist_r;
//#line 26 "../cfg/MyStuff.cfg"
      double grasp1_r;
//#line 27 "../cfg/MyStuff.cfg"
      double grasp2_r;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("MyStuffConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const MyStuffConfig &__max__ = __getMax__();
      const MyStuffConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const MyStuffConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const MyStuffConfig &__getDefault__();
    static const MyStuffConfig &__getMax__();
    static const MyStuffConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const MyStuffConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void MyStuffConfig::ParamDescription<std::string>::clamp(MyStuffConfig &config, const MyStuffConfig &max, const MyStuffConfig &min) const
  {
    return;
  }

  class MyStuffConfigStatics
  {
    friend class MyStuffConfig;
    
    MyStuffConfigStatics()
    {
//#line 13 "../cfg/MyStuff.cfg"
      __min__.shoulder_l = -50.0;
//#line 13 "../cfg/MyStuff.cfg"
      __max__.shoulder_l = 50.0;
//#line 13 "../cfg/MyStuff.cfg"
      __default__.shoulder_l = 0.0;
//#line 13 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("shoulder_l", "double", 0, "An offet to add to the shoulder_l", "", &MyStuffConfig::shoulder_l)));
//#line 14 "../cfg/MyStuff.cfg"
      __min__.elbow_l = -50.0;
//#line 14 "../cfg/MyStuff.cfg"
      __max__.elbow_l = 50.0;
//#line 14 "../cfg/MyStuff.cfg"
      __default__.elbow_l = 0.0;
//#line 14 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("elbow_l", "double", 0, "An offet to add to the elbow_l", "", &MyStuffConfig::elbow_l)));
//#line 15 "../cfg/MyStuff.cfg"
      __min__.insertion_l = -50.0;
//#line 15 "../cfg/MyStuff.cfg"
      __max__.insertion_l = 50.0;
//#line 15 "../cfg/MyStuff.cfg"
      __default__.insertion_l = 0.0;
//#line 15 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("insertion_l", "double", 0, "An offet to add to the insertion_l", "", &MyStuffConfig::insertion_l)));
//#line 16 "../cfg/MyStuff.cfg"
      __min__.roll_l = -50.0;
//#line 16 "../cfg/MyStuff.cfg"
      __max__.roll_l = 50.0;
//#line 16 "../cfg/MyStuff.cfg"
      __default__.roll_l = 0.0;
//#line 16 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("roll_l", "double", 0, "An offet to add to the roll_l", "", &MyStuffConfig::roll_l)));
//#line 17 "../cfg/MyStuff.cfg"
      __min__.wrist_l = -50.0;
//#line 17 "../cfg/MyStuff.cfg"
      __max__.wrist_l = 50.0;
//#line 17 "../cfg/MyStuff.cfg"
      __default__.wrist_l = 0.0;
//#line 17 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("wrist_l", "double", 0, "An offet to add to the wrist_l", "", &MyStuffConfig::wrist_l)));
//#line 18 "../cfg/MyStuff.cfg"
      __min__.grasp1_l = -50.0;
//#line 18 "../cfg/MyStuff.cfg"
      __max__.grasp1_l = 50.0;
//#line 18 "../cfg/MyStuff.cfg"
      __default__.grasp1_l = 0.0;
//#line 18 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp1_l", "double", 0, "An offet to add to the grasp1_l", "", &MyStuffConfig::grasp1_l)));
//#line 19 "../cfg/MyStuff.cfg"
      __min__.grasp2_l = -50.0;
//#line 19 "../cfg/MyStuff.cfg"
      __max__.grasp2_l = 50.0;
//#line 19 "../cfg/MyStuff.cfg"
      __default__.grasp2_l = 0.0;
//#line 19 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp2_l", "double", 0, "An offet to add to the grasp2_l", "", &MyStuffConfig::grasp2_l)));
//#line 21 "../cfg/MyStuff.cfg"
      __min__.shoulder_r = -50.0;
//#line 21 "../cfg/MyStuff.cfg"
      __max__.shoulder_r = 50.0;
//#line 21 "../cfg/MyStuff.cfg"
      __default__.shoulder_r = 0.0;
//#line 21 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("shoulder_r", "double", 0, "An offet to add to the shoulder_r", "", &MyStuffConfig::shoulder_r)));
//#line 22 "../cfg/MyStuff.cfg"
      __min__.elbow_r = -50.0;
//#line 22 "../cfg/MyStuff.cfg"
      __max__.elbow_r = 50.0;
//#line 22 "../cfg/MyStuff.cfg"
      __default__.elbow_r = 0.0;
//#line 22 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("elbow_r", "double", 0, "An offet to add to the elbow_r", "", &MyStuffConfig::elbow_r)));
//#line 23 "../cfg/MyStuff.cfg"
      __min__.insertion_r = -50.0;
//#line 23 "../cfg/MyStuff.cfg"
      __max__.insertion_r = 50.0;
//#line 23 "../cfg/MyStuff.cfg"
      __default__.insertion_r = 0.0;
//#line 23 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("insertion_r", "double", 0, "An offet to add to the shoulder_r", "", &MyStuffConfig::insertion_r)));
//#line 24 "../cfg/MyStuff.cfg"
      __min__.roll_r = -50.0;
//#line 24 "../cfg/MyStuff.cfg"
      __max__.roll_r = 50.0;
//#line 24 "../cfg/MyStuff.cfg"
      __default__.roll_r = 0.0;
//#line 24 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("roll_r", "double", 0, "An offet to add to the roll_r", "", &MyStuffConfig::roll_r)));
//#line 25 "../cfg/MyStuff.cfg"
      __min__.wrist_r = -50.0;
//#line 25 "../cfg/MyStuff.cfg"
      __max__.wrist_r = 50.0;
//#line 25 "../cfg/MyStuff.cfg"
      __default__.wrist_r = 0.0;
//#line 25 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("wrist_r", "double", 0, "An offet to add to the wrist_r", "", &MyStuffConfig::wrist_r)));
//#line 26 "../cfg/MyStuff.cfg"
      __min__.grasp1_r = -50.0;
//#line 26 "../cfg/MyStuff.cfg"
      __max__.grasp1_r = 50.0;
//#line 26 "../cfg/MyStuff.cfg"
      __default__.grasp1_r = 0.0;
//#line 26 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp1_r", "double", 0, "An offet to add to the grasp1_r", "", &MyStuffConfig::grasp1_r)));
//#line 27 "../cfg/MyStuff.cfg"
      __min__.grasp2_r = -50.0;
//#line 27 "../cfg/MyStuff.cfg"
      __max__.grasp2_r = 50.0;
//#line 27 "../cfg/MyStuff.cfg"
      __default__.grasp2_r = 0.0;
//#line 27 "../cfg/MyStuff.cfg"
      __param_descriptions__.push_back(MyStuffConfig::AbstractParamDescriptionConstPtr(new MyStuffConfig::ParamDescription<double>("grasp2_r", "double", 0, "An offet to add to the grasp2_r", "", &MyStuffConfig::grasp2_r)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<MyStuffConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<MyStuffConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    MyStuffConfig __max__;
    MyStuffConfig __min__;
    MyStuffConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const MyStuffConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static MyStuffConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &MyStuffConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const MyStuffConfig &MyStuffConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const MyStuffConfig &MyStuffConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const MyStuffConfig &MyStuffConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<MyStuffConfig::AbstractParamDescriptionConstPtr> &MyStuffConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const MyStuffConfigStatics *MyStuffConfig::__get_statics__()
  {
    const static MyStuffConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = MyStuffConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __MYSTUFFRECONFIGURATOR_H__
