(cl:in-package raven_2-msg)
(cl:export '(HDR-VAL
          HDR
          RUNLEVEL-VAL
          RUNLEVEL
          SUBLEVEL-VAL
          SUBLEVEL
          LAST_SEQ-VAL
          LAST_SEQ
          TYPE-VAL
          TYPE
          POS-VAL
          POS
          ORI-VAL
          ORI
          ORI_D-VAL
          ORI_D
          POS_D-VAL
          POS_D
          DT-VAL
          DT
          ENCVALS-VAL
          ENCVALS
          DAC_VAL-VAL
          DAC_VAL
          TAU-VAL
          TAU
          MPOS-VAL
          MPOS
          JPOS-VAL
          JPOS
          MVEL-VAL
          MVEL
          JVEL-VAL
          JVEL
          MPOS_D-VAL
          MPOS_D
          JPOS_D-VAL
          JPOS_D
          GRASP_D-VAL
          GRASP_D
          ENCOFFSETS-VAL
          ENCOFFSETS
          JAC_VEL-VAL
          JAC_VEL
          JAC_F-VAL
          JAC_F
))